# This image used Alpine
FROM ghcr.io/jesusfernxndez/developer-container:main

# Example install nodejs npm pnpm with Alpine
# RUN apk add --no-cache nodejs npm pnpm

# Set `DEVCONTAINER` environment variable para que VS Code lo reconozca
ENV DEVCONTAINER=true
