# This image used Ubuntu
FROM ghcr.io/jesusfernxndez/developer-container:main

# Example install nodejs using fnm
# developer-container image already has zsh, zinit and starship installed
# RUN zsh -l -c 'curl -fsSL https://fnm.vercel.app/install | bash \
#     && source $HOME/.zshrc \
#     && fnm install --latest'

# Set `DEVCONTAINER` environment variable to true
ENV DEVCONTAINER=true
